### PR TITLE
Newaudit

### PR DESCRIPTION
**Pull request by jcriotte**

### CODE REVIEW

**Review by aldaitzwild — CHANGES_REQUESTED** [review]
No ! I told it was ok to commit your modification despite the ExcessivePublicCount   error and the TooManyFields error from grump, but here you have a third error : "ExcessiveMethodLength". Your method is too long. Cut it in three smaller ones

**Comment by jcriotte** [comment]
But, Thomas, the problem is still related to the large number of questions related to the audit questionnaire. Besides, I only asked half the questions! How do you do that?

**Comment by jcriotte** [comment]
I remain available to exchange on the discord

**Comment by jcriotte** [comment]
I want to get it right, but this....

**Review by aldaitzwild — APPROVED** [review]

**Pull request merged**
